# NumPy

In [12]:
import numpy as np

# create an array of random elements with shape 2, 3, 4
data = np.random.rand(2, 3, 4)
# create an array of zeroes with shape 2, 2, 2
zeroes = np.zeros((2, 2, 2))
# create an array of ones with shape 2, 2, 2
ones = np.ones((2, 2, 2))
# create an array of <n> with shape 2, 2, 2
full = np.full((2, 2, 2), 7)

print(data)
print(zeroes)
print(ones)
print(full)

[[[0.1353629  0.87572044 0.39445497 0.60144973]
  [0.92840782 0.54526281 0.75463459 0.48092887]
  [0.23799462 0.24203026 0.62334647 0.35199257]]

 [[0.80319554 0.822218   0.72857951 0.92217097]
  [0.69245555 0.94475156 0.06947593 0.84504294]
  [0.03448742 0.78303173 0.65204828 0.69555765]]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


## Array attributes

In [13]:
shape =  data.shape
size = data.size
types = data.dtype

print(shape)
print(size)
print(types)

(2, 3, 4)
24
float64


In [14]:
## Array slicing

In [15]:
first_array = data[0]
sliced = data[0:2]
last_array = data[-1]
single_value = data[0][0][0]

print(first_array)
print(sliced)
print(last_array)
print(single_value)

[[0.1353629  0.87572044 0.39445497 0.60144973]
 [0.92840782 0.54526281 0.75463459 0.48092887]
 [0.23799462 0.24203026 0.62334647 0.35199257]]
[[[0.1353629  0.87572044 0.39445497 0.60144973]
  [0.92840782 0.54526281 0.75463459 0.48092887]
  [0.23799462 0.24203026 0.62334647 0.35199257]]

 [[0.80319554 0.822218   0.72857951 0.92217097]
  [0.69245555 0.94475156 0.06947593 0.84504294]
  [0.03448742 0.78303173 0.65204828 0.69555765]]]
[[0.80319554 0.822218   0.72857951 0.92217097]
 [0.69245555 0.94475156 0.06947593 0.84504294]
 [0.03448742 0.78303173 0.65204828 0.69555765]]
0.13536289634579013


## Array math

In [18]:
array1 = np.random.rand(10)
array2 = np.random.rand(10)

sum = np.add(array1, array2)
diff = np.subtract(array1, array2)
quotient = np.divide(array1, array2)
product = np.multiply(array1, array2)

print(sum)
print(diff)
print(quotient)
print(product)

[0.29971601 0.55436103 1.70843433 1.17538528 0.68860787 0.84090523
 1.67996571 1.1188988  1.03125174 1.14482446]
[ 0.16356265  0.38307204 -0.18776135  0.45681248  0.21881634  0.14826286
  0.21958965  0.7964406   0.1580458   0.21583659]
[3.40262395 5.47281582 0.80195994 2.27144384 1.93154656 1.42810797
 1.30073027 5.9398067  1.36198974 1.46467042]
[0.01576924 0.04014299 0.72087339 0.29321323 0.10657505 0.17128493
 0.6935163  0.15440423 0.25962542 0.3160094 ]


## Dot product

For 1-D arrays (Vectors), dot computes the dot product of the two vectors. For 2-D arrays, dot performs matrix multiplication. For N-D arrays, dot performs a generalized dot product, summing the product of elements ofver the last axis of the first array and the second-to-last axis of the second array.

In [19]:
dot = np.dot(array1, array2)

print(dot)

2.77141416935783


## NumPy Boolean operations

NumPy arrays do not support and, or, and not.  
Instead, np.logical_and(bool, bool) and it's related functions are available.

In [17]:
import numpy as np

arr1 = np.array([12, 456, 32, 1, 234, 10])
arr2 = np.array([29, 111, 98, 6, 773, 44])

ands = np.logical_and(arr1 > 20, arr2 > 20)
ors = np.logical_or(arr1 > 20, arr2 > 20)
nots = np.logical_not(arr1 > 20, arr2 > 20)

print(ands)
print(ors)
print(nots)

[False  True  True False  True False]
[ True  True  True False  True  True]
[ True False False  True False  True]


## Append / Insert

np.append takes two arguments:
- array being appended to
- element to append

np.insert takes three arguments:
- array taking an insertion
- insertion index
- element to insert

In [20]:
zeros = np.zeros((8))
print(zeros)

zeros = np.append(zeros, [3, 4]) 
print(zeros)

zeros = np.insert(zeros, 2, 1) 
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]
