# NumPy

In [5]:
import numpy as np

# create an array of random elements with shape 2, 3, 4
data = np.random.rand(2, 3, 4)
# create an array of zeroes with shape 2, 2, 2
zeroes = np.zeros((2, 2, 2))
# create an array of ones with shape 2, 2, 2
ones = np.ones((2, 2, 2))
# create an array of <n> with shape 2, 2, 2
full = np.full((2, 2, 2), 7)

print(data)
print(zeroes)
print(ones)
print(full)

[[[0.46501841 0.05105642 0.89011601 0.01449786]
  [0.18469372 0.10800833 0.13895288 0.25431311]
  [0.24588607 0.28946891 0.42689732 0.25074096]]

 [[0.76777495 0.91576501 0.85663157 0.74390436]
  [0.37838761 0.72572824 0.85603525 0.27984121]
  [0.06361733 0.38751395 0.38725512 0.62437827]]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


## Array attributes

In [6]:
shape =  data.shape
size = data.size
types = data.dtype

print(shape)
print(size)
print(types)

(2, 3, 4)
24
float64


## Array slicing

In [7]:
first_array = data[0]
sliced = data[0:2]
last_array = data[-1]
single_value = data[0][0][0]

print(first_array)
print(sliced)
print(last_array)
print(single_value)

[[0.46501841 0.05105642 0.89011601 0.01449786]
 [0.18469372 0.10800833 0.13895288 0.25431311]
 [0.24588607 0.28946891 0.42689732 0.25074096]]
[[[0.46501841 0.05105642 0.89011601 0.01449786]
  [0.18469372 0.10800833 0.13895288 0.25431311]
  [0.24588607 0.28946891 0.42689732 0.25074096]]

 [[0.76777495 0.91576501 0.85663157 0.74390436]
  [0.37838761 0.72572824 0.85603525 0.27984121]
  [0.06361733 0.38751395 0.38725512 0.62437827]]]
[[0.76777495 0.91576501 0.85663157 0.74390436]
 [0.37838761 0.72572824 0.85603525 0.27984121]
 [0.06361733 0.38751395 0.38725512 0.62437827]]
0.4650184104263375


## Array math

In [8]:
array1 = np.random.rand(10)
array2 = np.random.rand(10)

sum = np.add(array1, array2)
diff = np.subtract(array1, array2)
quotient = np.divide(array1, array2)
product = np.multiply(array1, array2)

print(sum)
print(diff)
print(quotient)
print(product)

[0.84814075 0.94485193 1.16510929 1.27024479 1.09079092 0.52444716
 0.46590499 0.34434473 1.01932501 1.43188973]
[ 0.23566017  0.22564692  0.77681384 -0.22158655 -0.52731101  0.23686783
  0.20024058 -0.26554618  0.71437655  0.28846523]
[1.76952701 1.62748985 5.00114831 0.70293351 0.34823511 2.64732164
 2.50747012 0.12920107 5.68522808 1.50456366]
[0.16595176 0.21045716 0.18850998 0.3911053  0.22794198 0.05473461
 0.04424279 0.01201463 0.13217241 0.49177401]


## Dot product

For 1-D arrays (Vectors), dot computes the dot product of the two vectors. For 2-D arrays, dot performs matrix multiplication. For N-D arrays, dot performs a generalized dot product, summing the product of elements ofver the last axis of the first array and the second-to-last axis of the second array.

In [9]:
dot = np.dot(array1, array2)

print(dot)

1.9189046289694187


## NumPy Boolean operations

NumPy arrays do not support and, or, and not.  
Instead, np.logical_and(bool, bool) and it's related functions are available.

In [10]:
import numpy as np

arr1 = np.array([12, 456, 32, 1, 234, 10])
arr2 = np.array([29, 111, 98, 6, 773, 44])

ands = np.logical_and(arr1 > 20, arr2 > 20)
ors = np.logical_or(arr1 > 20, arr2 > 20)
nots = np.logical_not(arr1 > 20, arr2 > 20)

print(ands)
print(ors)
print(nots)

[False  True  True False  True False]
[ True  True  True False  True  True]
[ True False False  True False  True]


## Stat functions

In [11]:
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2, 7)
log = np.log(25)
exp = np.exp([2, 3])
mins = np.min(array1)
maxs = np.max(array2)

print(sqrt)
print(ab)
print(power)
print(log)
print(exp)
print(mins)
print(maxs)

5.0
2
128
3.2188758248682006
[ 7.3890561  20.08553692]
0.03939927834751744
0.8090509659534323


## Append / Insert

np.append takes two arguments:
- array being appended to
- element to append

np.insert takes three arguments:
- array taking an insertion
- insertion index
- element to insert

In [12]:
zeros = np.zeros((8))
print(zeros)

zeros = np.append(zeros, [3, 4]) 
print(zeros)

zeros = np.insert(zeros, 2, 1) 
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


## Reshape a dataset

## Loop over NumPy arrays

np.nditer() provides iterable functionality for np arrays, allowing access to variables nested in N-D arrays

In [13]:
random_array = np.random.rand(2, 3, 4)
for i in np.nditer(random_array):
    print(i)

0.7174040801185293
0.800016073791161
0.5403494519148737
0.49993127895142175
0.2704489754151549
0.26322089592650044
0.1785922813648182
0.6288657235163713
0.7342220297910622
0.7566842137171851
0.08353596125402307
0.14992650115938988
0.7546554000950326
0.7823621749933001
0.5627922576649905
0.3465379294250912
0.43760109733460895
0.39138640925694324
0.6306706177967687
0.17844363212814018
0.9222912131291015
0.22976322186540377
0.6454486115072855
0.3606783777500957
